### ISSUE TITLE
please publish latest to npm

### ISSUE THREAD

**Issue by danwulff** [Maloric/tslint-jasmine-noSkipOrFocus#7]
It looks like your latest change (updating the tslint peer dependency to be less strict). Didn't get published to npm as this is what I currently see in my package.json
`
"peerDependencies": {
    "tslint": ">=4.5.1  <=5.5.0"
  },
`

Could you publish the lastest? Thanks.

**Comment by stocksr** [comment]
would love to but #8 is blocking me and work deadlines mean I don't have time to investigate at the moment.

**Comment by danwulff** [comment]
I left a comment on #8, let me know if I can help.

**Comment by stocksr** [comment]
done
